### ISSUE TITLE
ImportError: cannot import name 'Tracker'

### ISSUE THREAD

**Issue by NickShargan** [ModelChimp/modelchimp#1]
Following [documentation](https://docs.modelchimp.com/) I have installed modelchimp:

`pip3 install -U modelchimp`

But when I am trying to import Tracker from modelchimp receive ImportError:

```
>>> import modelchimp
>>> from modelchimp import Tracker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Tracker'
```

Also I can't find Tracker class in [modelchimp repository](https://github.com/ModelChimp/modelchimp) and [modelchimp-client repository](https://github.com/ModelChimp/modelchimp-client)

**Comment by NickShargan** [comment]
The problem was that I tried to run example in modelchimp (cloned repository) directory.

**Comment by samzer** [comment]
Ah cool :)
