### ISSUE TITLE
Change admin password

### ISSUE THREAD

**Issue by asafl** [ModelChimp/modelchimp#14]
How can I change the Administrator password? 
Thanks!

**Comment by samzer** [comment]
In the runserver.sh file, you'll find a line with create_super_user. You can edit the username and pass there.  After the first run, you can remove that line from the script if you want to.

https://github.com/ModelChimp/modelchimp/blob/master/runserver.sh

**Comment by asafl** [comment]
Thanks. Is there a way to change the password after the first run?

**Comment by samzer** [comment]
For now, you can shell into the docker conatiner

```sh
docker exec -i -t web  /bin/bash
```

Use this command to change the password

```sh
python manage.py changepassword admin@modelchimp.com
```

I'll be pushing an update tomorrow which exposes the admin page on the url http://<host>/hq from which the password can be updated via UI.

**Comment by asafl** [comment]
Worked. Thanks!
