### ISSUE TITLE
Allow encryption of model parameters

### ISSUE THREAD

**Issue by bollu** [ModelChimp/modelchimp#17]
It would be great if it's possible to encrypt model data and its hyperparameters, since this is getting uploaded to the ModelChimp hub.

**Comment by samzer** [comment]
A new feature called assets will be released next week. The serialized model can be stored in the asset section. If one wants to encrypt the model file then that can be done at the client side  and the encrypted model can be stored in modelchimp.

The remaining meta data that is sent is stored in a postgres db. If you are using the open source version then you can enable the encryption of the postgres at file system level. The hosted version of modelchimp uses amazon rds which handles this on its own.
