### ISSUE TITLE
Which host should be specified when server is running on localhost

### ISSUE THREAD

**Issue by NickShargan** [ModelChimp/modelchimp#2]
I've started modelchimp server [using docker](https://github.com/ModelChimp/modelchimp#docker) and can open it on localhost:8000. After creating project, inserting key and running [keras_example.py](https://docs.modelchimp.com/keras/) any new information appears on server.

As I understand for resolving this, host name in keras_example.py should be changed. I've tried:

1. demo.modelchimp.com
1. localhost
1. localhost:8000

But any run make changes on server. 

Which host should be specified for local run?

**Comment by samzer** [comment]
The 3rd option as the server is running on localhost:8000, the code at the client will look like as follows 

tracker = Tracker('<PROJECT KEY>', host='localhost:8000', experiment_name='MNIST Classification')

Also, I'll update the docs and sample projects with a comment regarding running on localhost.

**Comment by samzer** [comment]
There was a bug in 0.4.15 version which has been rectified in 0.4.17 of the client. Upgrade the client to the latest version with the following command and the metrics should appear after that.

pip3 install --upgrade --no-cache-dir modelchimp

**Comment by NickShargan** [comment]
Now it is working. I've upgraded modelchimp before but expected that new experiment  is on the bottom of the list while it is on the top.
