### ISSUE TITLE
Compared to MLFlow / ModelDB / Polyaxon

### ISSUE THREAD

**Issue by elgalu** [ModelChimp/modelchimp#23]
How does this project compares to MLFlow / ModelDB / Polyaxon?

Is it better support for real-time? or multi-tenancy? something else?

Thanks in advance.

**Comment by samzer** [comment]
Hey Leo,

Compared to Mlflow and ModelDB, Modelchimp has:
- **Realtime:** Realtime status of the currently running experiment and real-time epoch metric graphs
- **Storage of assets with meta information:** Useful post forensic prediction on images and text where the metric associated with each prediction is stored
- **Collaboration:** Define a single project and have multiple team members track the experiments at a single place
- **Code Snapshot:** Code used for the particular experiment. ( Mlflow stores the current git commit id )

ModelDB is more focussed on machine learning algorithms.  They have formed a company around it called Verta.ai and they'll be releasing a V2 version which will have support for deep learning.  

I wasn't aware of Polyaxon and looking at their webpage, it seems really cool. It looks like the most holistic solution out there. 

Hope this answer your questions.

**Comment by elgalu** [comment]
Ping @mouradmourafiq from Polyaxon; you have been praised:)

**Comment by elgalu** [comment]
thanks!!
