### ISSUE TITLE
'InMemoryUploadedFile' object has no attribute '_size'

### ISSUE THREAD

**Issue by agalst** [ModelChimp/modelchimp#4]
Hi,

I cloned the master branch, and run the server using docker. When I tried to update my profile with a jpg 175 KB photo, I got the following error:

Request Method: | POST
-- | --
http://localhost:8000/profile/
2.1.3
AttributeError
'InMemoryUploadedFile' object has no attribute '_size'
/code/modelchimp/forms/profile.py in clean_avatar, line 47
/usr/local/bin/python3
3.6.7
['/code',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/code']

**Comment by samzer** [comment]
Thanks for reporting the error.

Just pushed in the fix to the master. It should work now after pulling the latest master.

**Comment by agalst** [comment]
Great!
